Escolar32/Models/Receita.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

namespace Escolar32.Models
{
    public class Receita
    {
        public int ReceitaId { get; set; }

        [Display(Name = "Nome da Receita")]
        public string ReceitaNome { get; set;}

        [Column(TypeName = "decimal(10,2)")]
        [Display(Name = "Valor")]
        public decimal ValorReceita { get; set; }

        [Required]
        [Display(Name = "Data")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = false)]
        [BindProperty, DataType(DataType.Date)]
        public DateTime DataReceita{ get; set; }

        [Display(Name = "Detalhe da Receita")]
        public string ReceitaDetalhe { get; set; }

        [Display(Name = "Receita do Mês")]
        public int MesReceita { get; set; }
        
        [Display(Name = "Receita do Ano")]
        public int AnoReceita { get; set; }

    }
}

Escolar32/Areas/Admin/Controllers/ReceitasController.cs
using Escolar32.Context;
using Escolar32.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Escolar32.Areas.Admin.Services;

namespace Escolar32.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ReceitasController : Controller
    {
        private readonly AppDbContext _context;
        private readonly RelatorioReceitaService _relatorioReceitaService;

        public ReceitasController(AppDbContext context, RelatorioReceitaService relatorioReceitaService)
        {
            _context = context;
            _relatorioReceitaService = relatorioReceitaService;

        }
        
        // GET: ReceitasController
        public async Task<IActionResult> Receitas()
        {
            return View(await _context.Receitas.ToListAsync());
        }        

        //Relatorio de Receitas por período
        public async Task<IActionResult> ReceitaFiltro(DateTime? minDate,
            DateTime? maxDate)
        {
            if (!minDate.HasValue)
            {
                minDate = new DateTime(DateTime.Now.Year, 1, 1);
            }
            if (!maxDate.HasValue)
            {
                maxDate = DateTime.Now;
            }

            ViewData["minDate"] = minDate.Value.ToString("yyyy-MM-dd");
            ViewData["maxDate"] = maxDate.Value.ToString("yyyy-MM-dd");

            var result = await _relatorioReceitaService.FindByDateAsync(minDate, maxDate);
            return View(result);
        }

        // GET: Admin/Receita/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Receita/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReceitaId,ReceitaNome,ValorReceita,DataReceita,ReceitaDetalhe,ReceitaMes,ReceitaAno")] Receita receita)
        {
            if (ModelState.IsValid)
            {
                _context.Add(receita);
                receita.MesReceita = receita.DataReceita.Month;
                receita.AnoReceita = receita.DataReceita.Year;
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Receitas));
            }
            return View(receita);
        }

        // GET: ReceitasController/Details/5        
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Receitas == null)
            {
                return NotFound();
            }

            var receita = await _context.Receitas
                .FirstOrDefaultAsync(m => m.ReceitaId == id);
            if (receita == null)
            {
                return NotFound();
            }

            return View(receita);
        }

        // GET: Admin/Receita/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Receitas == null)
            {
                return NotFound();
            }

            var receita = await _context.Receitas.FindAsync(id);
            if (receita == null)
            {
                return NotFound();
            }
            return View(receita);
        }

        // POST: Admin/Receita/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReceitaId,ReceitaNome,ValorReceita,DataReceita,ReceitaDetalhe,MesReceita,AnoReceita")] Receita receita)
        {
            if (id != receita.ReceitaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(receita);
                    receita.MesReceita = receita.DataReceita.Month;
                    receita.AnoReceita = receita.DataReceita.Year;
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReceitaExists(receita.ReceitaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Receitas));
            }
            return View(receita);
        }

        // GET: Admin/Receita/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Receitas == null)
            {
                return NotFound();
            }

            var receita = await _context.Receitas
                .FirstOrDefaultAsync(m => m.ReceitaId == id);
            if (receita == null)
            {
                return NotFound();
            }

            return View(receita);
        }

        // POST: Admin/Receita/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Receitas == null)
            {
                return Problem("Entity set 'AppDbContext.Receitas' is null.");
            }
            var receita = await _context.Receitas.FindAsync(id);
            if (receita != null)
            {
                _context.Receitas.Remove(receita);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Receitas));
        }

        private bool ReceitaExists(int id)
        {
            return _context.Receitas.Any(e => e.ReceitaId == id);
        }

    }
}

Escolar32/Areas/Admin/Views/Receitas/Create.cshtml
@model Escolar32.Models.Receita

<h1>Cadastro de Receita</h1>

<hr />
<div class="row" style="margin-left: 50px;">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ReceitaNome" class="control-label"></label>
                <input asp-for="ReceitaNome" class="form-control" />
                <span asp-validation-for="ReceitaNome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorReceita" class="control-label"></label>
                <input asp-for="ValorReceita" class="form-control"
                       oninput="window.formatDecimalInput(this)"
                       onblur="window.formatOnBlur(this)" />
                <span asp-validation-for="ValorReceita" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataReceita" class="control-label"></label>
                <input asp-for="DataReceita" class="form-control" />
                <span asp-validation-for="DataReceita" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReceitaDetalhe" class="control-label"></label>
                <input asp-for="ReceitaDetalhe" class="form-control" />
                <span asp-validation-for="ReceitaDetalhe" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-area="Admin" asp-controller="Receitas" asp-action="Receitas">Voltar</a>
</div>

Escolar32/Areas/Admin/Views/Receitas/Delete.cshtml
@model Escolar32.Models.Receita

<h1>Apagar Despesa</h1>

<div>
    <h4>Despesa</h4>
    <hr />
    <dl class="row" style="margin-left: 50px;">
        <dt class = "col-sm-12">
            @Html.DisplayNameFor(model => model.ReceitaNome)
        </dt>
        <dd class = "col-sm-12">
            @Html.DisplayFor(model => model.ReceitaNome)
        </dd>
        <dt class="col-sm-12">
            @Html.DisplayNameFor(model => model.DataReceita)
        </dt>
        <dd class="col-sm-12">
            @Html.DisplayFor(model => model.DataReceita)
        </dd>
        <dt class="col-sm-12">
            @Html.DisplayNameFor(model => model.ReceitaDetalhe)
        </dt>
        <dd class="col-sm-12">
            @Html.DisplayFor(model => model.ReceitaDetalhe)
        </dd>
        <dt class = "col-sm-12">
            @Html.DisplayNameFor(model => model.ValorReceita)
        </dt>
        <dd class = "col-sm-12">
            @Html.DisplayFor(model => model.ValorReceita)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ReceitaId" />
        <input type="submit" value="Apagar" class="btn btn-danger" /> |
        <a asp-action="Despesas">Voltar para a lista</a>
    </form>
</div>

Escolar32/Areas/Admin/Views/Receitas/Edit.cshtml
@model Escolar32.Models.Receita

<h1>Editar</h1>

<hr />
<div class="row" style="margin-left: 50px;">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ReceitaId" />
            <div class="form-group">
                <label asp-for="ReceitaNome" class="control-label"></label>
                <input asp-for="ReceitaNome" class="form-control" />
                <span asp-validation-for="ReceitaNome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorReceita" class="control-label"></label>
                <input asp-for="ValorReceita" class="form-control"
                       oninput="window.formatDecimalInput(this)"
                       onblur="window.formatOnBlur(this)" />
                <span asp-validation-for="ValorReceita" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataReceita" class="control-label"></label>
                <input asp-for="DataReceita" class="form-control" />
                <span asp-validation-for="DataReceita" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReceitaDetalhe" class="control-label"></label>
                <input asp-for="ReceitaDetalhe" class="form-control" />
                <span asp-validation-for="ReceitaDetalhe" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Editar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Receitas">Voltar</a>
</div>

Escolar32/Areas/Admin/Views/Receitas/ReceitaFiltro.cshtml
@model IEnumerable<Escolar32.Models.Receita>
<div class="col-md-12">
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.ReceitaNome)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DataReceita)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ReceitaDetalhe)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ValorReceita)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @{
                    decimal totalReceita = 0;
                    var orderedModel = Model.OrderBy(item => item.DataReceita);
                    var rowClass = "even-row";

                    foreach (var item in orderedModel)
                    {
                        totalReceita += item.ValorReceita;
                        <tr class="@rowClass">
                            <td>
                                @Html.DisplayFor(modelItem => item.ReceitaNome)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DataReceita)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ReceitaDetalhe)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ValorReceita)
                            </td>
                            <td>
                                <a class="fa-solid fa-trash-can red-icon" asp-action="Delete" asp-route-id="@item.ReceitaId"></a>
                                <a class="fa-regular fa-pen-to-square" asp-action="Edit" asp-route-id="@item.ReceitaId"></a>
                            </td>
                        </tr>
                        rowClass = (rowClass == "even-row") ? "odd-row" : "even-row";
                    }
                    <tr>
                        <td></td>
                        <td colspan="2" style="text-align: center; font-weight: bold">Total das Receitas</td>
                        <td><strong>@totalReceita</strong></td>

                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div>
        <a asp-action="Receitas">Voltar</a>
    </div>
</div>

Escolar32/Areas/Admin/Views/Receitas/Receitas.cshtml
@model IEnumerable<Escolar32.Models.Receita>

<div class="container">

    <div class="row" style="margin-left: 50px;">
        <div class="col-md-6">
            <form class="form-horizontal" asp-action="ReceitaFiltro">
                <fieldset>
                    <legend><b>Relatório de Receitas por Período</b></legend>
                    <div class="form-group row">
                        <label for="minDate" class="col-lg-3 control-label">Data Inicial</label>
                        <div class="col-lg-4">
                            <input type="date" name="minDate" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="maxDate" class="col-lg-3 control-label">Data Final</label>
                        <div class="col-lg-4">
                            <input type="date" name="maxDate" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-lg-12 text-right">
                            <button type="submit" class="btn btn-outline-primary">Filtrar</button>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>

        <div>
            <strong>Nova Receita</strong>
            <a class="fa-solid fa-file-circle-plus green-icon" asp-action="Create"></a>
        </div>       

        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.ReceitaNome)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.DataReceita)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ReceitaDetalhe)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ValorReceita)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        decimal totalReceita = 0;
                        var orderedModel = Model.OrderByDescending(item => item.DataReceita);
                        var rowClass = "even-row";

                        foreach (var item in orderedModel)
                        {
                            totalReceita += item.ValorReceita;
                            <tr class="@rowClass">
                                <td>
                                    @Html.DisplayFor(modelItem => item.ReceitaNome)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DataReceita)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ReceitaDetalhe)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ValorReceita)
                                </td>
                                <td>
                                    <a class="fa-solid fa-trash-can red-icon" asp-action="Delete" asp-route-id="@item.ReceitaId"></a>
                                    <a class="fa-regular fa-pen-to-square" asp-action="Edit" asp-route-id="@item.ReceitaId"></a>
                                </td>
                            </tr>
                            rowClass = (rowClass == "even-row") ? "odd-row" : "even-row";
                        }
                        <tr>
                            <td></td>
                            <td colspan="2" style="text-align: center; font-weight: bold">Total das Receitas</td>
                            <td><strong>@totalReceita</strong></td>

                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>